### ISSUE TITLE
No consumption recorded

### ISSUE THREAD

**Issue by JustApu** [tronikos/esphome-magnetometer-water-gas-meter#20]
Similar to https://github.com/tronikos/esphome-magnetometer-water-gas-meter/issues/6 I'm not getting any water consumption being recorded. 1" Neptune T-10 meter and EPS32 (https://www.amazon.com/dp/B0B18NK2MS) board, with ~ 20" of cabling between the ESP32 and GY-273 QMC5883L.

All three (x, y, z) fields seem to record changes when there is water flowing during calibration but I'm not getting any usage or flow values in Home Assistant. (No attempts at temperature calibration were done.)

(Screenshots taken with clothes washer running.)
<img width="1004" alt="Screenshot 2024-07-05 at 13 27 16" src="https://github.com/tronikos/esphome-magnetometer-water-gas-meter/assets/30990146/8509155f-ce00-4150-8fd6-7a9e83be54e5">
<img width="268" alt="Screenshot 2024-07-05 at 13 28 26" src="https://github.com/tronikos/esphome-magnetometer-water-gas-meter/assets/30990146/58e1f39f-4b51-4dcb-937d-e70b87c0da64">
<img width="268" alt="Screenshot 2024-07-05 at 13 29 12" src="https://github.com/tronikos/esphome-magnetometer-water-gas-meter/assets/30990146/850f8d54-c09c-4549-9056-2bd6ca3505e2">

[logs_water-meter_logs.txt](https://github.com/user-attachments/files/16112443/logs_water-meter_logs.txt)

**Comment by tronikos** [comment]
Run a low flow water and click on calibrate. From your screenshots I see the thresholds are wrong. You should have -35 for the lower threshold and -25 for the upper threshold, i.e. +-5 points from the center point.
