### ISSUE TITLE
Gas flow refresh rate is not consistent while gas is flowing

### ISSUE THREAD

**Issue by sesardelaisla** [tronikos/esphome-magnetometer-water-gas-meter#3]
Hello! First of all, thanks for this awesome project. I was able to monitor the Schlumberger G2000 G4 gas meter that I have in my place, which is the model that my company installs in my area.

The issue I am experiencing is related to the flow rate. Every time the gas is flowing, the flow rate entity displays the value for a few seconds and then is set back to zero. After a few seconds, the flow rate is back to the right value and so on. Basically, the flow rate value is not constant when gas is flowing. I guess the refresh rate should be adjusted so it waits a bit more until the flow is assumed to be stopped. Is it possible to change this behaviour? TIA

**Comment by tronikos** [comment]
Fixed with https://github.com/tronikos/esphome-magnetometer-water-gas-meter/commit/d5b4805942299f4f4026c145e65b3ecc0805f4f6
I increased the flow update interval from 10s to 30s for gas meters. If that doesn't work try:

```yaml
substitutions:
  flow_update_interval_seconds: '60'
```

and let me know to make that the default for gas meters.
