### ISSUE TITLE
Gas Meter Reporting in Gal, instead of ft3 in home assistant

### ISSUE THREAD

**Issue by jsb2092** [tronikos/esphome-magnetometer-water-gas-meter#35]
My YAML has a substitution for the units to be ft3:
substitutions:
  volume_unit: 'ft³'
  unit_of_measurement: 'ft³'
  i2c_scl: GPIO4  # D1
  i2c_sda: GPIO3  # D2

  hide_magnetic_field_strength_sensors: 'true'
  hide_half_rotations_total_sensor: 'true'

packages:
  meter:
    url: https://github.com/tronikos/esphome-magnetometer-water-gas-meter
    ref: main
    file: esphome-gas-meter.yaml
    # Or for gas meter:
    # file: esphome-gas-meter.yaml
    # Or if you are using HMC5883L instead of QMC5883L:
    # files: [esphome-water-meter.yaml, hmc5883l.yaml]
    refresh: 0s
    

However, in Home Assistant, it is reporting gal for the unit.

<img width="300" alt="image" src="https://github.com/user-attachments/assets/e3aded1e-83ce-41db-8615-4e88081fa4db">
but the flow rate is the correct unit
<img width="312" alt="image" src="https://github.com/user-attachments/assets/bcf22036-44bb-4a16-969e-312c54134558">

**Comment by jsb2092** [comment]
This appears to be a HA issue, closing

**Comment by tronikos** [comment]
You can manually change the unit in HA in the settings of the entity.
