### ISSUE TITLE
Axis and threshold values are reset every time the ESP32 is disconnected

### ISSUE THREAD

**Issue by sesardelaisla** [tronikos/esphome-magnetometer-water-gas-meter#4]
Hello,

I have realized that threshold values are reset every time that my ESP32 ATOM Lite is disconnected or restarted for any reason. Once the ESP32 is back, values are not persistent. For the moment, I have created an automation for the purpose of setting the right values for axis, low and right thresholds every time such values change. However, I consider this as a workaround. Would it be possible for these values to be consistent?

TIA

**Comment by tronikos** [comment]
Fixed in https://github.com/tronikos/esphome-magnetometer-water-gas-meter/commit/0212843c97f33d454f3a4fa923510077e8baafe1

**Comment by jbronikowski** [comment]
This issue seems to happen on the latest build. Just lost power to my esp and this caused all settings to go back to default

**Comment by micle546** [comment]
My axis is also resetting on power cycle with the latest build

**Comment by tronikos** [comment]
Do you have the following per the README?

```yaml
preferences:
  flash_write_interval: 60min
```
