### ISSUE TITLE
Adjust Delta for gas meters

### ISSUE THREAD

**Issue by DenelDuck** [tronikos/esphome-magnetometer-water-gas-meter#45]
From the discussions here, the HA forums and my own experience, it seems that the magnetic field measurements on gas meters are way lower and have a less (also inconsistent) spread than water meters (e.g. only a spread of 20 µT).

Looking around in the `esphome-magnetometer.yaml` I saw that the delta for the measurements is set to 3 by default. This results in less usable measurements if the spread is only about 20. The curve sometimes falls short and it is hard to find a working lower/upper threshold. The image below demonstrates how inconsistent the readings are and it is almost impossible to distinguish the pulses. 
![image](https://github.com/user-attachments/assets/8b71a319-fc60-4c33-b8fd-258f17dc1d9c)

I worked around this by lowering the delta (I first lowered it to 0.1, but that seemed unnecessarily low, so i changed it to 0.2) and this really improved the measurements and consistency. In the image below you can see that it is really easy to distinguish the pulses and thus also set a working lower/upper threshold.
![image](https://github.com/user-attachments/assets/1a21e2ee-1683-4c27-8832-bfa84060b552)

I'm totally new to this HA thing, so I don't know if it is possible to integrate something that allows a user to easily change these deltas? It took me quite some time to figure this out because the `esphome-magnetometer.yaml` file has quite some lines so it is not very straightforward.

**Comment by tronikos** [comment]
The delta is only used for the values reported to Home Assistant. Internally for computing the flow I use on_raw_value. I could add a substitution for the delta but I don't see the need. You are only meant to have these sensors enabled during calibration anyway. There is no reason to overwhelm Home Assistant recorder updating its database so frequently and there is no reason slowing down the ESP controller trying to send updates to Home Assistant so frequently.
